
<div class="social-media-buttons">
    <div class="fb-like" data-href="<?php echo $this->getCanonicalUrl() ?>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
    <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
    <a data-pin-config="beside" href="//pinterest.com/pin/create/button/?url=<?php echo urlencode($this->getCanonicalUrl()) ?>&media=<?php echo urlencode($this->getProductImageUrl()) ?>&description=<?php echo urlencode($this->getProductDescription()) ?>" data-pin-do="buttonPin" ><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
    <div class="g-plusone" data-href="<?php echo urlencode($this->getCanonicalUrl()) ?>" data-size="medium"></div>
</div>

<div id="fb-root"></div>

<script type="text/javascript">
    // load JS asynchronously
    (function(doc, script) {
        var js,
            fjs = doc.getElementsByTagName(script)[0],
            add = function(url, id) {
                if (doc.getElementById(id)) {return;}
                js = doc.createElement(script);
                js.src = url;
                id && (js.id = id);
                fjs.parentNode.insertBefore(js, fjs);
            };

        // Google+ button
        add('//apis.google.com/js/plusone.js');
        // Facebook SDK
        add('//connect.facebook.net/en_GB/all.js#xfbml=1', 'facebook-jssdk');
        // Twitter SDK
        add('//platform.twitter.com/widgets.js', 'twitter-wjs');
        // Pinterest
        add('//assets.pinterest.com/js/pinit.js');
    }(document, 'script'));
</script>